# Generated by Django 5.1.15 on 2026-05-08 21:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_name', models.CharField(blank=True, help_text='Como o paciente prefere ser chamado. Usado em devolutivas e pelo psicólogo.', max_length=120, verbose_name='nome preferido')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='data de nascimento')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patient_profile', to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
            options={
                'verbose_name': 'perfil de paciente',
                'verbose_name_plural': 'perfis de paciente',
            },
        ),
        migrations.CreateModel(
            name='PsychologistProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crp_number', models.CharField(blank=True, help_text='Número do CRP (Conselho Regional de Psicologia). Validação de formato é futura.', max_length=20, verbose_name='CRP')),
                ('bio', models.TextField(blank=True, verbose_name='biografia profissional')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='psychologist_profile', to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
            options={
                'verbose_name': 'perfil de psicólogo',
                'verbose_name_plural': 'perfis de psicólogo',
            },
        ),
    ]
