# Generated by Django 5.1.15 on 2026-05-09 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_provider_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientprofile',
            name='preferred_name',
            field=models.CharField(blank=True, help_text='Como o paciente prefere ser chamado. Usado em devolutivas e pelo profissional.', max_length=120, verbose_name='nome preferido'),
        ),
    ]
