# Generated by Django 5.1.15 on 2026-05-13 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_patientprofile_preferred_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthcareprovider',
            name='stripe_customer_id',
            field=models.CharField(blank=True, db_index=True, max_length=64, verbose_name='Stripe customer id'),
        ),
        migrations.AddField(
            model_name='healthcareprovider',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, max_length=64, verbose_name='Stripe subscription id'),
        ),
        migrations.AlterField(
            model_name='healthcareprovider',
            name='plan',
            field=models.CharField(choices=[('basic', 'Básico'), ('pro', 'Pro'), ('premium', 'Premium')], default='basic', help_text='Tier de assinatura. Define acesso a IA e cota — ver ADR 0010. Profissional novo nasce em Básico (sem IA) por default. Alterado apenas via webhook da Stripe (ADR 0012).', max_length=10, verbose_name='plano'),
        ),
    ]
