# Generated by Django 5.1.15 on 2026-05-08 21:17

import apps.bonds.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_patientprofile_psychologistprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bond',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invite_code', models.CharField(db_index=True, default=apps.bonds.models.generate_invite_code, max_length=12, unique=True, verbose_name='código de convite')),
                ('status', models.CharField(choices=[('invited', 'Convite gerado'), ('pending', 'Aguardando confirmação do psicólogo'), ('active', 'Ativo'), ('ended', 'Encerrado')], default='invited', max_length=16, verbose_name='status')),
                ('invited_at', models.DateTimeField(auto_now_add=True, verbose_name='convite criado em')),
                ('patient_entered_at', models.DateTimeField(blank=True, null=True, verbose_name='paciente entrou em')),
                ('psychologist_confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='psicólogo confirmou em')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='encerrado em')),
                ('ended_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ended_bonds', to=settings.AUTH_USER_MODEL, verbose_name='encerrado por')),
                ('patient', models.ForeignKey(blank=True, help_text='Nulo enquanto o paciente ainda não inseriu o código de convite.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bonds', to='accounts.patientprofile', verbose_name='paciente')),
                ('psychologist', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bonds', to='accounts.psychologistprofile', verbose_name='psicólogo')),
            ],
            options={
                'verbose_name': 'vínculo',
                'verbose_name_plural': 'vínculos',
                'ordering': ('-invited_at',),
                'constraints': [models.UniqueConstraint(condition=models.Q(('status__in', ('invited', 'pending', 'active'))), fields=('psychologist', 'patient'), name='unique_alive_bond_per_pair'), models.CheckConstraint(condition=models.Q(('status', 'invited'), ('patient__isnull', False), _connector='OR'), name='bond_patient_required_after_invite')],
            },
        ),
    ]
