# Generated by Django 5.1.15 on 2026-05-13 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonds', '0002_rename_psychologist_to_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='bond',
            name='invitee_label',
            field=models.CharField(blank=True, help_text='Memo livre — nome, email ou referência do paciente para quem o convite foi gerado. Visível apenas para o profissional. Não compartilhado nem validado contra dados reais — serve só para o profissional lembrar a quem mandou o código.', max_length=120, verbose_name='destinatário (memo)'),
        ),
    ]
