# Generated by Django 5.1.15 on 2026-05-13 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(db_index=True, help_text='Identificador único do evento na Stripe (formato `evt_...`). Unique constraint garante processamento exatamente uma vez.', max_length=128, unique=True, verbose_name='Stripe event id')),
                ('event_type', models.CharField(db_index=True, max_length=64, verbose_name='tipo do evento')),
                ('payload', models.JSONField(help_text='Objeto completo do evento conforme recebido da Stripe. Útil para debug e re-processamento manual. Não contém dados de cartão (Stripe não envia PAN/CVV por webhook).', verbose_name='payload')),
                ('received_at', models.DateTimeField(auto_now_add=True, verbose_name='recebido em')),
                ('processed_at', models.DateTimeField(blank=True, help_text='Quando o handler terminou sem erro. Vazio = falhou ou ignorado.', null=True, verbose_name='processado em')),
                ('error', models.TextField(blank=True, help_text='Traceback / mensagem se o handler falhou. Vazio = sucesso.', verbose_name='erro')),
            ],
            options={
                'verbose_name': 'evento da Stripe',
                'verbose_name_plural': 'eventos da Stripe',
                'ordering': ('-received_at',),
                'indexes': [models.Index(fields=['-received_at'], name='billing_web_receive_20b8b6_idx')],
            },
        ),
    ]
