# Generated by Django 5.1.15 on 2026-05-09 12:58

import django.db.models.deletion
import django_cryptography.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0005_alter_patientprofile_preferred_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientOverview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', django_cryptography.fields.encrypt(models.TextField(blank=True, verbose_name='resumo'))),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('last_edited_by', models.ForeignKey(blank=True, help_text='Profissional que editou o resumo pela última vez.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='overviews_edited', to='accounts.healthcareprovider', verbose_name='último editor')),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='overview', to='accounts.patientprofile', verbose_name='paciente')),
            ],
            options={
                'verbose_name': 'resumo do paciente',
                'verbose_name_plural': 'resumos do paciente',
            },
        ),
        migrations.CreateModel(
            name='PatientReportedMedication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', django_cryptography.fields.encrypt(models.TextField(help_text='Liste o que está tomando — receitas atuais, OTC, suplementos. É auto-reporte; o profissional usa como contexto clínico.', verbose_name='medicações que estou tomando'))),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported_medications', to='accounts.patientprofile', verbose_name='paciente')),
            ],
            options={
                'verbose_name': 'medicação auto-reportada',
                'verbose_name_plural': 'medicações auto-reportadas',
            },
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', django_cryptography.fields.encrypt(models.CharField(max_length=200, verbose_name='medicamento'))),
                ('dosage', django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=120, verbose_name='dosagem'))),
                ('frequency', django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=120, verbose_name='frequência'))),
                ('notes', django_cryptography.fields.encrypt(models.TextField(blank=True, verbose_name='observações'))),
                ('started_at', models.DateField(blank=True, null=True, verbose_name='iniciada em')),
                ('ended_at', models.DateField(blank=True, help_text='Vazio = em uso. Preencher quando descontinuar.', null=True, verbose_name='descontinuada em')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='registrada em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizada em')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medications', to='accounts.patientprofile', verbose_name='paciente')),
                ('prescribed_by', models.ForeignKey(help_text='Psiquiatra que fez a prescrição.', on_delete=django.db.models.deletion.PROTECT, related_name='prescriptions', to='accounts.healthcareprovider', verbose_name='prescrito por')),
            ],
            options={
                'verbose_name': 'medicação prescrita',
                'verbose_name_plural': 'medicações prescritas',
                'ordering': ('-started_at', '-created_at'),
                'indexes': [models.Index(fields=['patient', '-started_at'], name='clinical_me_patient_985fd2_idx')],
            },
        ),
    ]
