# Generated by Django 5.1.15 on 2026-05-08 21:50

import django.db.models.deletion
import django_cryptography.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_patientprofile_psychologistprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoodEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mood', models.IntegerField(choices=[(1, 'Muito triste 😢'), (2, 'Triste ☹'), (3, 'Neutro 😐'), (4, 'Bem 🙂'), (5, 'Muito bem 😊')], verbose_name='humor')),
                ('content', django_cryptography.fields.encrypt(models.TextField(blank=True, verbose_name='conteúdo'))),
                ('is_shared_with_psychologist', models.BooleanField(default=False, help_text='Default privado — compartilhamento é decisão consciente do paciente.', verbose_name='compartilhar com psicólogo')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mood_entries', to='accounts.patientprofile', verbose_name='paciente')),
            ],
            options={
                'verbose_name': 'registro de humor',
                'verbose_name_plural': 'registros de humor',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['patient', '-created_at'], name='journal_moo_patient_6116be_idx')],
            },
        ),
    ]
