# Generated by Django 5.1.15 on 2026-05-08 22:28

import django.db.models.deletion
import django_cryptography.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_patientprofile_psychologistprofile'),
        ('bonds', '0001_initial'),
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicalNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', django_cryptography.fields.encrypt(models.TextField(verbose_name='conteúdo'))),
                ('session_date', models.DateField(blank=True, help_text='Opcional. Data da sessão à qual a nota se refere.', null=True, verbose_name='data da sessão')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('bond', models.ForeignKey(help_text='Define implicitamente o psicólogo (autor) e o paciente (sujeito).', on_delete=django.db.models.deletion.PROTECT, related_name='clinical_notes', to='bonds.bond', verbose_name='vínculo')),
            ],
            options={
                'verbose_name': 'anotação clínica',
                'verbose_name_plural': 'anotações clínicas',
                'ordering': ('-session_date', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('situation', 'Situação vivida'), ('thought', 'Pensamento'), ('dream', 'Sonho'), ('reflection', 'Reflexão')], default='situation', max_length=16, verbose_name='tipo')),
                ('title', models.CharField(blank=True, help_text='Opcional. Ajuda a localizar o registro depois.', max_length=200, verbose_name='título')),
                ('content', django_cryptography.fields.encrypt(models.TextField(verbose_name='conteúdo'))),
                ('mood', models.IntegerField(blank=True, choices=[(1, 'Muito triste 😢'), (2, 'Triste ☹'), (3, 'Neutro 😐'), (4, 'Bem 🙂'), (5, 'Muito bem 😊')], null=True, verbose_name='humor associado')),
                ('is_shared_with_psychologist', models.BooleanField(default=False, verbose_name='compartilhar com psicólogo')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='journal_entries', to='accounts.patientprofile', verbose_name='paciente')),
            ],
            options={
                'verbose_name': 'entrada do diário',
                'verbose_name_plural': 'entradas do diário',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='MoodLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mood', models.IntegerField(choices=[(1, 'Muito triste 😢'), (2, 'Triste ☹'), (3, 'Neutro 😐'), (4, 'Bem 🙂'), (5, 'Muito bem 😊')], verbose_name='humor')),
                ('is_shared_with_psychologist', models.BooleanField(default=False, verbose_name='compartilhar com psicólogo')),
                ('recorded_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='registrado em')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mood_logs', to='accounts.patientprofile', verbose_name='paciente')),
            ],
            options={
                'verbose_name': 'registro de humor',
                'verbose_name_plural': 'registros de humor',
                'ordering': ('-recorded_at',),
            },
        ),
        migrations.DeleteModel(
            name='MoodEntry',
        ),
        migrations.AddIndex(
            model_name='clinicalnote',
            index=models.Index(fields=['bond', '-created_at'], name='journal_cli_bond_id_78bb39_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['patient', '-created_at'], name='journal_jou_patient_32b184_idx'),
        ),
        migrations.AddIndex(
            model_name='moodlog',
            index=models.Index(fields=['patient', '-recorded_at'], name='journal_moo_patient_df3226_idx'),
        ),
    ]
