# Generated by Django 5.1.15 on 2026-05-08 23:15

import django.db.models.deletion
import django_cryptography.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_patientprofile_psychologistprofile'),
        ('bonds', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AISummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('weekly_patient', 'Resumo semanal (paciente)'), ('session_briefing', 'Briefing pré-sessão (psicólogo)')], max_length=24, verbose_name='tipo')),
                ('content', django_cryptography.fields.encrypt(models.TextField(verbose_name='conteúdo'))),
                ('period_start', models.DateTimeField(verbose_name='janela início')),
                ('period_end', models.DateTimeField(verbose_name='janela fim')),
                ('model_used', models.CharField(max_length=64, verbose_name='modelo')),
                ('token_metadata', models.JSONField(default=dict, verbose_name='metadata de tokens')),
                ('generated_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='gerado em')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ai_summaries_requested', to=settings.AUTH_USER_MODEL, verbose_name='solicitado por')),
                ('target_bond', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ai_summaries', to='bonds.bond', verbose_name='vínculo alvo')),
                ('target_patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ai_summaries', to='accounts.patientprofile', verbose_name='paciente alvo')),
            ],
            options={
                'verbose_name': 'resumo de IA',
                'verbose_name_plural': 'resumos de IA',
                'ordering': ('-generated_at',),
                'indexes': [models.Index(fields=['kind', '-generated_at'], name='ai_aisummar_kind_b08aa3_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('kind', 'weekly_patient'), ('target_bond__isnull', True), ('target_patient__isnull', False)), models.Q(('kind', 'session_briefing'), ('target_bond__isnull', False), ('target_patient__isnull', True)), _connector='OR'), name='aisummary_kind_target_consistency')],
            },
        ),
    ]
