# Generated by Django 5.1.15 on 2026-05-13 20:57

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0002_aiusagecounter'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='aiusagecounter',
            new_name='ai_aiusagec_provide_3b8e75_idx',
            old_name='ai_aiusageco_provide_3df1d2_idx',
        ),
        migrations.AddField(
            model_name='aiusagecounter',
            name='cost_brl',
            field=models.DecimalField(decimal_places=6, default=Decimal('0'), help_text='Custo total de chamadas à LLM no período, em reais.', max_digits=10, verbose_name='custo acumulado (R$)'),
        ),
    ]
