# Generated by Django 5.1.15 on 2026-05-08 21:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(db_index=True, help_text="Identificador da ação. Convenção: 'app.evento', ex.: 'bond.confirmed'.", max_length=64, verbose_name='ação')),
                ('target_type', models.CharField(blank=True, help_text="Nome do modelo do alvo (ex.: 'Bond', 'MoodEntry'). Vazio se ação não tem alvo.", max_length=64, verbose_name='tipo do alvo')),
                ('target_id', models.BigIntegerField(blank=True, help_text='PK do alvo. Não é FK pra preservar histórico após delete cascade.', null=True, verbose_name='ID do alvo')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='timestamp')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='metadata')),
                ('actor', models.ForeignKey(blank=True, help_text='Usuário que executou a operação. Nulo apenas em ações de sistema.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='ator')),
            ],
            options={
                'verbose_name': 'registro de auditoria',
                'verbose_name_plural': 'registros de auditoria',
                'ordering': ('-timestamp',),
                'indexes': [models.Index(fields=['target_type', 'target_id'], name='audit_audit_target__2d648a_idx'), models.Index(fields=['actor', '-timestamp'], name='audit_audit_actor_i_dcd783_idx')],
            },
        ),
    ]
